variables:
  APP_IMAGE: "osl_app"
  COMPOSE_FILE: "docker-compose.build.yml"
  CONTAINER_RELEASE_IMAGE: "nanawel/our-shopping-list"
  CONTAINER_PUBLIC_IMAGE: "nanawel/our-shopping-list"

stages:
  - check
  - build
  - release

before_script:
  - time docker info
  - '[ -z "${REGISTRY_SERVER}" ] || time docker login ${REGISTRY_SERVER}'
  - env

build_image:
  stage: build
  script:
    - time make config
    - export buildVersion=$([ -z "${CI_COMMIT_TAG}" ] && echo ${CI_COMMIT_REF_SLUG} || echo ${CI_COMMIT_TAG})
      && time make build args="--build-arg build_version=${buildVersion} --build-arg build_id=${CI_COMMIT_SHORT_SHA} --build-arg build_date=$(date -Is)"
    - time docker tag ${APP_IMAGE}:${APP_VERSION:-latest} ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
  tags:
    - shell
    - docker

push_image_latest:
  stage: release
  script:
    - time docker pull ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_RELEASE_IMAGE}:latest
    - time docker push ${CONTAINER_RELEASE_IMAGE}:latest
  tags:
    - shell
    - docker
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "master"'

push_image_tagged:
  stage: release
  script:
    - time docker pull ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_TAG}
    - time docker push ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_TAG}
  tags:
    - shell
    - docker
  rules:
    - if: '$CI_COMMIT_TAG =~ /^\d+\.\d+\.\d+$/'

push_image_public:
  stage: release
  script:
    - docker login -u "${PUBLIC_REGISTRY_USERNAME}" -p "${PUBLIC_REGISTRY_TOKEN}"
    - time docker pull ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA}
    - time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_PUBLIC_IMAGE}:latest
    - time docker push ${CONTAINER_PUBLIC_IMAGE}:latest
    - '[ -z "${CI_COMMIT_TAG}" ] || time docker tag ${CONTAINER_RELEASE_IMAGE}:${CI_COMMIT_SHORT_SHA} ${CONTAINER_PUBLIC_IMAGE}:${CI_COMMIT_TAG}'
    - '[ -z "${CI_COMMIT_TAG}" ] || time docker push ${CONTAINER_PUBLIC_IMAGE}:${CI_COMMIT_TAG}'
  tags:
    - shell
    - docker
  rules:
    - when: manual
      if: '$CONTAINER_RELEASE_IMAGE != $CONTAINER_PUBLIC_IMAGE'
