version: '3.2'

services:
  app:
    image: node:${node_version}${node_variant_dev}
    working_dir: /app
    command: '${NODE_BIN:-node} index.js'
    ports:
      - '8080:8080'
      - '8081:8081'
      - '8888:8888'   # Webpack Bundle Analyzer
      - '9229:9229'   # Debugger
    volumes:
      - ./server:/app
      - ./client:/app/client
    environment:
      NODE_ENV: development
      ENABLE_TLS: 1
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
